apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-jpmk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-jpmk
    app.kubernetes.io/part-of: ci10t-777-0051-app
  name: devfile-sample-jpmk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-jpmk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-jpmk
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0051-tenant/ci10t-777-0051-app/devfile-sample-jpmk@sha256:789c8f215e57b26d83b169d014fc9ed1d0796dca365080bd4957ccf4940967ad
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
